### ISSUE TITLE
[Server] Network Error, 서버 주소 변경

### ISSUE THREAD

**Issue by zirryo** [codestates-seb/seb40_main_033#308]
### 1. 원인
[메일 원문]
Amazon EC2 has detected degradation of the underlying hardware hosting your EC2 instance associated with your AWS account in the ap-northeast-2 region. This instance is scheduled for maintenance and will be rebooted any time between 2023-04-12 02:00:00 UTC and 2023-04-12 04:00:00 UTC. 

* What will happen to my instance during this maintenance event?

During maintenance, the instance will be rebooted. The reboot generally takes a few minutes to complete. After the reboot, your instance retains its IP address, DNS name, and any data on local instance-store volumes.
(이하 생략)

3월 말, AWS 에서 위와 같은 내용의 메일을 받았습니다. 
리부트 이후 별 문제없이 사용할 수 있다는 것으로 이해하여 별다른 조치를 취하지 않고 그대로 두었으나 현시점 기준 서버가 정상적으로 동작되지 않는 상황입니다.
4달간 서버 운영에 별다른 문제가 없었기에,  해당 이슈가 현 상황의 원인으로 추측됩니다.
 
</br>

### 2. 현재 상황

- 인스턴스 자체가 사라진 줄 알았으나, 기존 인스턴스 자체는 유지되어 있음. (IP 주소도 유지)
- 리부팅 과정에서 서버가 꺼진 것으로 예상됨.
- ec2에 연결하여 서버를 재작동해야 하나, 알 수 없는 이유로 어떤 방식으로도 ec2에 연결되지 않음.

</br>

### 3. 예상 소요 시간

~2023.04.18 23:59~

---

### 4. 해결
2023.04.15 15:30 기준 서버 재가동 중입니다.

기존 인스턴스를 불가피하게 중지 후 재시작 해야 하는 상황에 놓여 탄력적 IP 를 부여받은 후 재시작 하였습니다.
그러나, 탄력적 IP 를 부여받음과 동시에 기존 주소에서 변경이 발생했고, 앞으로의 중지 및 재시작에서는 현주소가 유지되겠지만 이미 기존 주소는 사용할 수 없게 되었습니다.
Postman 을 이용하여 새로운 주소에 요청을 보내본 결과, 응답에는 문제가 없는 것으로 확인됩니다.
다만, 프론트 쪽에 등록된 주소의 변경이 필요할 것 같습니다.

</br>

## 📑 체크리스트
- [x] 서버 정상화

**Comment by uxolrv** [comment]
오와아 인스턴스가 사라진 건 아니었군요!!?
변경된 서버 URL 주시면 바로 반영하도록 하겠습니다!!
수고하셨습니다ㅠ ㅠ 갓지효님 🥺 ✨
